from joblib import load
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import pandas as pd
distodoc_dict= {
    "Dermatologist": ["Fungal infection", "Acne", "Psoriasis", "Impetigo"],
    "Gastroenterologist": ["hepatitis A", "Hepatitis B", "Hepatitis C", "Hepatitis D", "Hepatitis E",
                           "Alcoholic hepatitis", "GERD", "Chronic cholestasis", "Peptic ulcer diseae",
                           "Gastroenteritis", "Jaundice"],
    "Pulmonologist": ["Tuberculosis", "Bronchial Asthma"],
    "General Physician": ["Common Cold", "AIDS", "Hypertension", "Malaria", "Chicken pox", "Dengue", "Typhoid"],
    "Lung Specialist": ["Pneumonia"],
    "Proctologist": ["Dimorphic hemmorhoids(piles)"],
    "Cardiologist": ["Heart attack"],
    "Vascular Surgeon": ["Varicose veins"],
    "Endocrinologist": ["Hypothyroidism", "Hyperthyroidism", "Hypoglycemia", "Diabetes"],
    "Rheumatologist": ["Osteoarthritis", "Arthritis"],
    "ENT Specialist": ["(vertigo) Paroymsal  Positional Vertigo"],
    "Urologist": ["Urinary Tract Infection"],
    "Allergist": ["Allergy", "Drug Reaction"],
    "Neurologist": ["Migraine", "Paralysis (brain hemorrhage)"],
    "Orthopaedic Surgeon": ["Cervical spondylosis"]
}
symtodis_dict={'(vertigo) Paroymsal  Positional Vertigo': ['nausea',
  'loss_of_balance',
  'unsteadiness',
  'spinning_movements',
  'vomiting',
  'headache'],
 'AIDS': [' high_fever',
  'patches_in_throat',
  'extra_marital_contacts',
  'muscle_wasting'],
 'Acne': ['skin_rash', 'scurring', 'pus_filled_pimples', 'blackheads'],
 'Alcoholic hepatitis': ['distention_of_abdomen',
  'history_of_alcohol_consumption',
  'fluid_overload',
  'yellowish_skin',
  'swelling_of_stomach',
  'vomiting',
  'abdominal_pain'],
 'Allergy': ['shivering',
  'watering_from_eyes',
  'continuous_sneezing',
  'chills'],
 'Arthritis': ['movement_stiffness',
  'painful_walking',
  'swelling_joints',
  'muscle_weakness',
  'stiff_neck'],
 'Bronchial Asthma': ['high_fever',
  'family_history',
  'fatigue',
  'cough',
  'mucoid_sputum',
  'breathlessness'],
 'Cervical spondylosis': ['back_pain',
  'neck_pain',
  'loss_of_balance',
  'dizziness',
  'weakness_in_limbs'],
 'Chicken pox': ['loss_of_appetite',
  'itching',
  'high_fever',
  'skin_rash',
  'lethargy',
  'swelled_lymph_nodes',
  'fatigue',
  'malaise',
  'headache',
  'red_spots_over_body',
  'mild_fever'],
 'Chronic cholestasis': ['loss_of_appetite',
  'itching',
  'nausea',
  'yellowish_skin',
  'vomiting',
  'yellowing_of_eyes',
  'abdominal_pain'],
 'Common Cold': ['muscle_pain',
  'high_fever',
  'congestion',
  'redness_of_eyes',
  'loss_of_smell',
  'continuous_sneezing',
  'swelled_lymph_nodes',
  'fatigue',
  'cough',
  'malaise',
  'throat_irritation',
  'sinus_pressure',
  'chest_pain',
  'headache',
  'phlegm',
  'runny_nose',
  'chills'],
 'Dengue': ['loss_of_appetite',
  'joint_pain',
  'skin_rash',
  'high_fever',
  'nausea',
  'back_pain',
  'muscle_pain',
  'pain_behind_the_eyes',
  'fatigue',
  'malaise',
  'vomiting',
  'headache',
  'red_spots_over_body',
  'chills'],
 'Diabetes ': ['polyuria',
  'excessive_hunger',
  'lethargy',
  'irregular_sugar_level',
  'increased_appetite',
  'fatigue',
  'weight_loss',
  'blurred_and_distorted_vision',
  'obesity',
  'restlessness'],
 'Dimorphic hemmorhoids(piles)': ['pain_during_bowel_movements',
  'bloody_stool',
  'pain_in_anal_region',
  'irritation_in_anus',
  'constipation'],
 'Drug Reaction': ['itching',
  'skin_rash',
  'spotting_ urination',
  'stomach_pain',
  'burning_micturition'],
 'Fungal infection': ['itching',
  'skin_rash',
  'nodal_skin_eruptions',
  'dischromic _patches'],
 'GERD': ['cough',
  'chest_pain',
  'stomach_pain',
  'vomiting',
  'ulcers_on_tongue',
  'acidity'],
 'Gastroenteritis': ['sunken_eyes',
  'vomiting',
  'dehydration',
  'diarrhoea'],
 'Heart attack': ['chest_pain', 'vomiting', 'sweating', 'breathlessness'],
 'Hepatitis B': ['loss_of_appetite',
  'tching',
  'lethargy',
  'fatigue',
  'receiving_unsterile_injections',
  'yellowish_skin',
  'malaise',
  'yellowing_of_eyes',
  'dark_urine',
  'yellow_urine',
  'abdominal_pain',
  'receiving_blood_transfusion'],
 'Hepatitis C': ['loss_of_appetite',
  'nausea',
  'family_history',
  'fatigue',
  'yellowish_skin',
  'yellowing_of_eyes'],
 'Hepatitis D': ['loss_of_appetite',
  'joint_pain',
  'nausea',
  'fatigue',
  'yellowish_skin',
  'vomiting',
  'yellowing_of_eyes',
  'dark_urine',
  'abdominal_pain'],
 'Hepatitis E': ['loss_of_appetite',
  'joint_pain',
  'high_fever',
  'nausea',
  'fatigue',
  'yellowish_skin',
  'vomiting',
  'yellowing_of_eyes',
  'dark_urine',
  'coma',
  'abdominal_pain',
  'stomach_bleeding',
  'acute_liver_failure'],
 'Hypertension ': ['lack_of_concentration',
  'loss_of_balance',
  'chest_pain',
  'dizziness',
  'headache'],
 'Hyperthyroidism': ['excessive_hunger',
  'irritability',
  'fatigue',
  'weight_loss',
  'sweating',
  'fast_heart_rate',
  'abnormal_menstruation',
  'muscle_weakness',
  'restlessness',
  'diarrhoea',
  'mood_swings'],
 'Hypoglycemia': ['excessive_hunger',
  'nausea',
  'drying_and_tingling_lips',
  'fatigue',
  'palpitations',
  'slurred_speech',
  'vomiting',
  'anxiety',
  'blurred_and_distorted_vision',
  'headache',
  'sweating',
  'irritability'],
 'Hypothyroidism': ['weight_gain',
  'lethargy',
  'cold_hands_and_feets',
  'brittle_nails',
  'fatigue',
  'enlarged_thyroid',
  'depression',
  'puffy_face_and_eyes',
  'swollen_extremeties',
  'dizziness',
  'abnormal_menstruation',
  'irritability',
  'mood_swings'],
 'Impetigo': ['skin_rash',
  'high_fever',
  'blister',
  'red_sore_around_nose',
  'yellow_crust_ooze'],
 'Jaundice': ['itching',
  'high_fever',
  'fatigue',
  'weight_loss',
  'yellowish_skin',
  'vomiting',
  'dark_urine',
  'abdominal_pain'],
 'Malaria': ['muscle_pain',
  'high_fever',
  'nausea',
  'vomiting',
  'headache',
  'sweating',
  'diarrhoea',
  'chills'],
 'Migraine': ['excessive_hunger',
  'visual_disturbances',
  'depression',
  'blurred_and_distorted_vision',
  'headache',
  'acidity',
  'irritability',
  'stiff_neck',
  'indigestion'],
 'Osteoarthristis': ['joint_pain',
  'neck_pain',
  'hip_joint_pain',
  'knee_pain',
  'painful_walking',
  'swelling_joints'],
 'Paralysis (brain hemorrhage)': ['altered_sensorium',
  'weakness_of_one_body_side',
  'vomiting',
  'headache'],
 'Peptic ulcer diseae': ['loss_of_appetite',
  'vomiting',
  'passage_of_gases',
  'abdominal_pain',
  'internal_itching',
  'indigestion'],
 'Pneumonia': ['high_fever',
  'fatigue',
  'cough',
  'malaise',
  'chest_pain',
  'phlegm',
  'rusty_sputum',
  'sweating',
  'fast_heart_rate',
  'breathlessness',
  'chills'],
 'Psoriasis': ['joint_pain',
  'skin_rash',
  'silver_like_dusting',
  'skin_peeling',
  'small_dents_in_nails',
  'inflammatory_nails'],
 'Tuberculosis': ['loss_of_appetite',
  'high_fever',
  'swelled_lymph_nodes',
  'fatigue',
  'weight_loss',
  'cough',
  'malaise',
  'chest_pain',
  'vomiting',
  'yellowing_of_eyes',
  'phlegm',
  'sweating',
  'blood_in_sputum',
  'breathlessness',
  'mild_fever',
  'chills'],
 'Typhoid': ['high_fever',
  'nausea',
  'fatigue',
  'diarrhoea',
  'belly_pain',
  'vomiting',
  'toxic_look_(typhos)',
  'headache',
  'abdominal_pain',
  'constipation',
  'chills'],
 'Urinary tract infection': ['continuous_feel_of_urine',
  'bladder_discomfort',
  'foul_smell_of urine',
  'burning_micturition'],
 'Varicose veins': ['prominent_veins_on_calf',
  'swollen_legs',
  'swollen_blood_vessels',
  'fatigue',
  'cramps',
  'bruising',
  'obesity'],
 'hepatitis A': ['loss_of_appetite',
  'joint_pain',
  'muscle_pain',
  'nausea',
  'yellowish_skin',
  'mild_fever',
  'vomiting',
  'yellowing_of_eyes',
  'dark_urine',
  'abdominal_pain',
  'diarrhoea']}


class DiseasetoDoctor:
    def findDoc(self, *symps):
        model = load('symptoms-disease_model.joblib')
        lis = MultiLabelBinarizer(classes=['abdominal_pain', 'abnormal_menstruation', 'acidity',
                                           'acute_liver_failure', 'altered_sensorium', 'anxiety',
                                           'back_pain', 'belly_pain', 'blackheads', 'bladder_discomfort',
                                           'blister', 'blood_in_sputum', 'bloody_stool',
                                           'blurred_and_distorted_vision', 'breathlessness',
                                           'brittle_nails', 'bruising', 'burning_micturition',
                                           'chest_pain', 'chills', 'cold_hands_and_feets', 'coma',
                                           'congestion', 'constipation', 'continuous_feel_of_urine',
                                           'continuous_sneezing', 'cough', 'cramps', 'dark_urine',
                                           'dehydration', 'depression', 'diarrhoea',
                                           'dischromic_patches', 'distention_of_abdomen', 'dizziness',
                                           'drying_and_tingling_lips', 'enlarged_thyroid',
                                           'excessive_hunger', 'extra_marital_contacts', 'family_history',
                                           'fast_heart_rate', 'fatigue', 'fluid_overload',
                                           'foul_smell_of urine', 'headache', 'high_fever',
                                           'hip_joint_pain', 'history_of_alcohol_consumption',
                                           'increased_appetite', 'indigestion', 'inflammatory_nails',
                                           'internal_itching', 'irregular_sugar_level', 'irritability',
                                           'irritation_in_anus', 'joint_pain', 'knee_pain',
                                           'lack_of_concentration', 'lethargy', 'loss_of_appetite',
                                           'loss_of_balance', 'loss_of_smell', 'malaise', 'mild_fever',
                                           'mood_swings', 'movement_stiffness', 'mucoid_sputum',
                                           'muscle_pain', 'muscle_wasting', 'muscle_weakness', 'nausea',
                                           'neck_pain', 'nodal_skin_eruptions', 'obesity',
                                           'pain_behind_the_eyes', 'pain_during_bowel_movements',
                                           'pain_in_anal_region', 'painful_walking', 'palpitations',
                                           'passage_of_gases', 'patches_in_throat', 'phlegm', 'polyuria',
                                           'prominent_veins_on_calf', 'puffy_face_and_eyes',
                                           'pus_filled_pimples', 'receiving_blood_transfusion',
                                           'receiving_unsterile_injections', 'red_sore_around_nose',
                                           'red_spots_over_body', 'redness_of_eyes', 'restlessness',
                                           'runny_nose', 'rusty_sputum', 'scurring', 'shivering',
                                           'silver_like_dusting', 'sinus_pressure', 'skin_peeling',
                                           'skin_rash', 'slurred_speech', 'small_dents_in_nails',
                                           'spinning_movements', 'spotting_urination', 'stiff_neck',
                                           'stomach_bleeding', 'stomach_pain', 'sunken_eyes', 'sweating',
                                           'swelled_lymph_nodes', 'swelling_joints', 'swelling_of_stomach',
                                           'swollen_blood_vessels', 'swollen_extremeties', 'swollen_legs',
                                           'throat_irritation', 'toxic_look_(typhos)', 'ulcers_on_tongue',
                                           'unsteadiness', 'visual_disturbances', 'vomiting',
                                           'watering_from_eyes', 'weakness_in_limbs',
                                           'weakness_of_one_body_side', 'weight_gain', 'weight_loss',
                                           'yellow_crust_ooze', 'yellow_urine', 'yellowing_of_eyes',
                                           'yellowish_skin', 'itching']).fit_transform(symps)
        pred = model.predict(np.array(lis))
        print(pred)
        for i in pred:
            p = i
        print(str(p))
        for key, value_list in distodoc_dict.items():
            if p in value_list:
                found_key = key
                break
        
        return [p, found_key]

# Ask the user for symptoms
def distodoc(dis):
    for key, value_list in distodoc_dict.items():
            if dis in value_list:
                found_key = key
                break
    return found_key
print("Please enter your symptoms separated by commas (e.g., cough, fever):")
user_input = input()
symptoms = user_input.split(",")
symptoms=set([i.strip() for i in symptoms])
total_symptoms=set([i for (key, val) in symtodis_dict.items() for i in val])
if(total_symptoms.issuperset(symptoms)):
    lis=[]
    for key, vals in symtodis_dict.items():
        valset=set(vals)
        if(symptoms.issubset(valset)):
            d={key:vals}
            lis.append(d)
    if(len(lis)==0):
        disease_to_doctor = DiseasetoDoctor()
        result = disease_to_doctor.findDoc(symptoms)   
        disease_name, doctor_name = result[0], result[1]
        print("\nDiagnosis Results:")
        print(f"Disease: {disease_name}")
        print(f"Recommended Doctor: {doctor_name}")
    else:
        print(lis)
else:
    print('This symptom is not in the list. Please check the list, and then correct it.')
    # Then we will put an option for user to select the disease
    # After which, we can put the disease name inside distodoc(disease_name), which will return the doctor name

